// Sentence mark-up annotations for "extra": arcs drawn above the sentence, captions under words, tense card.
// Format and how to add more: see the header of assets/js/markup.js and the README.
window.CEFR_DATA = window.CEFR_DATA || {};
window.CEFR_DATA.clues = window.CEFR_DATA.clues || {};
window.CEFR_DATA.clues.extra = {
  1: { links: [["tired", "get up", "เหนื่อย → ลุกจากเตียงไม่ไหว"], ["this morning", "get up", "ตอนเช้า"]], tags: [["get up", "ตื่น/ลุกจากเตียง"]], tip: "get up = ตื่นนอน/ลุกจากเตียง · get on = ขึ้น (รถ) · get off = ลง" },
  2: { links: [["too loud", "turn down", "ดังเกินไป → ลดเสียง"]], tags: [["turn down", "ลด (เสียง)"]], tip: "turn down = ลดเสียง/ลดความแรง · turn up = เพิ่มเสียง · turn on = เปิด" },
  3: { links: [["milk", "out of", "นมหมด → ran out of"]], tags: [["out of", "run out of"]], tip: "run out of + สิ่งของ = ของหมด (ran = past ของ run)" },
  4: { links: [["my keys", "for", "หา → look for"]], tags: [["for", "look for"]], tip: "look for = มองหา · look at = มอง · look after = ดูแล" },
  5: { links: [["both have curly hair", "after", "หน้าตาคล้าย → take after"]], tags: [["after", "take after"]], tip: "take after + ญาติ = หน้าตา/นิสัยคล้าย (พ่อ/แม่)" },
  6: { tense: "past-simple", links: [["landed", "took off", "ขึ้นบิน → ลงจอด"]], tags: [["took off", "V2"]], tip: "took off (V2) คู่กับ landed (V2) = เหตุการณ์ในอดีตเรียงตามลำดับ · take off = เครื่องบินขึ้น" },
  7: { links: [["before you come in", "take off", "ก่อนเข้า → ถอดรองเท้า"]], tags: [["take off", "ถอด"]], tip: "take off + เสื้อผ้า/รองเท้า = ถอดออก" },
  8: { tense: "past-simple", links: [["last year", "gave", "last year → อดีต"], ["smoking", "up", "give up + V-ing"]], tags: [["up", "give up = เลิก"]], tip: "give up + V-ing = เลิก... · gave = V2 (เพราะ last year)" },
  9: { links: [["Could you do me", "favour", "do someone a favour"]], tags: [["favour", "do a favour"]], tip: "do someone a favour = ช่วยเหลือสักอย่าง (collocation)" },
  10: { tense: "present-simple", links: [["Everyone", "makes", "make mistakes"], ["sometimes", "makes", "present simple"]], tags: [["makes", "make mistakes"]], tip: "make a mistake (ไม่ใช้ do) · Everyone = เอกพจน์ → makes" },
  11: { tense: "past-simple", links: [["was a long journey", "took", "อดีต → V2"]], tags: [["took", "take a break"]], tip: "take a break = พัก (collocation) · was (อดีต) → took (V2)" },
  12: { links: [["to the teacher", "pay", "pay attention"]], tags: [["pay", "pay attention to"]], tip: "pay attention to = ใส่ใจ/ตั้งใจฟัง (collocation)" },
  13: { links: [["photo", "take", "take a photo"]], tags: [["take", "take a photo"]], tip: "take a photo / picture = ถ่ายรูป · draw a picture = วาดรูป" },
  14: { tense: "past-simple", links: [["after the illness", "lost", "หลังป่วย → น้ำหนักลด"]], tags: [["lost", "lose weight (V2)"]], tip: "lose weight = น้ำหนักลด · เล่าเหตุการณ์ที่จบแล้ว → lost (V2)" },
  15: { links: [["from the cash machine", "withdraw", "ตู้ ATM → ถอนเงิน"]], tags: [["withdraw", "ถอนเงิน"]], tip: "withdraw = ถอนเงิน · deposit = ฝากเงิน · lend = ให้ยืม · owe = เป็นหนี้" },
  16: { links: [["I forgot mine", "lend", "ผมลืมเอามา → ขอให้ยืม"]], tags: [["lend", "lend me = ให้ฉันยืม"]], tip: "lend me = ให้ฉันยืม (เขาให้) · borrow from you = ฉันยืมมา" },
  17: { links: [["afraid", "of", "afraid of"]], tags: [["of", "afraid of"]], tip: "afraid of + นาม/V-ing = กลัว..." },
  18: { links: [["interested", "in", "interested in"]], tags: [["in", "interested in"]], tip: "interested in + นาม/V-ing = สนใจ..." },
  19: { links: [["married", "to", "married to"]], tags: [["to", "married to"]], tip: "be married to + คน = แต่งงานกับ... (ไม่ใช้ with)" },
  20: { links: [["arrived", "at", "arrive at + สถานที่เล็ก"]], tags: [["at", "arrive at / in"]], tip: "arrive at + สถานที่เฉพาะ (airport, station) · arrive in + เมือง/ประเทศ" },
  21: { links: [["apologised", "for", "apologise for"]], tags: [["for", "apologise for"]], tip: "apologise for + V-ing/นาม = ขอโทษที่... · apologise to + คน" },
  22: { links: [["depend", "on", "depend on"]], tags: [["on", "depend on"]], tip: "depend on = พึ่งพา/ขึ้นอยู่กับ" },
  23: { links: [["belongs", "to", "belong to"]], tags: [["to", "belong to"]], tip: "belong to + เจ้าของ = เป็นของ... (ไม่ใช้ of)" },
  24: { links: [["agree", "with", "agree with + คน"]], tags: [["with", "agree with"]], tip: "agree with + คน/ความคิดเห็น · agree to + แผน/ข้อเสนอ" },
  25: { links: [["What's the matter", "with", "matter with"]], tags: [["with", "the matter with"]], tip: "What's the matter with + คน? = (เขา) เป็นอะไร" },
  26: { links: [["proud", "of", "proud of"]], tags: [["of", "proud of"]], tip: "proud of = ภูมิใจใน..." },
  27: { links: [["a very", "talented", "a + adv + adj + noun"], ["singer", "talented", "adj ขยายนาม"]], tags: [["talented", "adjective"]], tip: "หน้านาม (singer) ต้องใช้คำคุณศัพท์ → talented (talent เป็นนาม)" },
  28: { links: [["answered", "correctly", "adverb ขยายกริยา"]], tags: [["correctly", "adverb (-ly)"]], tip: "ขยายกริยา (answered) → adverb: correct → correctly" },
  29: { links: [["The", "construction", "หลัง The ต้องเป็นนาม"], ["of the new bridge", "construction", "the ___ of ... = นาม"]], tags: [["construction", "noun"]], tip: "The ___ of ... = ต้องเป็นนาม → construction (การก่อสร้าง)" },
  30: { links: [["I was", "delighted", "รู้สึก → -ed"]], tags: [["delighted", "รู้สึกยินดี"]], tip: "คนรู้สึก → -ed (delighted) · be + adj" },
  31: { links: [["without a licence", "illegal", "ไม่มีใบขับขี่ → ผิดกฎหมาย"]], tags: [["illegal", "il- = ไม่"]], tip: "without a licence = ผิดกฎหมาย → il + legal = illegal (ไม่ใช่ unlegal)" },
  32: { links: [["spoke", "quietly", "adverb ขยาย spoke"], ["so", "quietly", "so + adv"]], tags: [["quietly", "adverb"]], tip: "ขยายกริยา (spoke) → adverb: quiet → quietly" },
  33: { links: [["The film", "boring", "สิ่งที่ทำให้รู้สึก → -ing"], ["fell asleep", "boring", "ผล: หลับ"]], tags: [["boring", "ทำให้เบื่อ"]], tip: "สิ่งของ/หนัง (ตัวที่ทำให้รู้สึก) → -ing (boring) · คนที่รู้สึก → -ed (bored)" },
  34: { links: [["I was", "interested", "คนรู้สึก → -ed"]], tags: [["interested", "รู้สึกสนใจ"]], tip: "คน (I) รู้สึก → -ed (interested) · สิ่งที่น่าสนใจ → interesting" },
  35: { links: [["Would you like some more tea?", "Yes, please", "เสนอ → ตอบรับสุภาพ"]], tags: [["Yes, please", "รับ (สุภาพ)"]], tip: "Would you like...? → ตอบรับ Yes, please. / ปฏิเสธ No, thank you." },
  36: { links: [["how do I get to the station", "Go straight", "ถามทาง → บอกทาง"]], tags: [["Go straight", "บอกทาง"]], tip: "ถามทาง (how do I get to) → ตอบด้วยคำสั่งบอกทาง (go straight, turn left)" },
  37: { links: [["I'm sorry I'm late", "That's okay", "ขอโทษ → ไม่เป็นไร"]], tags: [["That's okay", "ตอบรับคำขอโทษ"]], tip: "ขอโทษ → ตอบ That's okay / No problem. (You're welcome = ตอบคำขอบคุณ)" },
  38: { links: [["Thanks", "You're welcome", "ขอบคุณ → ไม่เป็นไร"]], tags: [["You're welcome", "ตอบรับคำขอบคุณ"]], tip: "ขอบคุณ → You're welcome. (ตอบรับคำขอบคุณ)" },
  39: { links: [["speak to Mr. Brown", "I'm afraid he's out", "ขอสาย → ไม่อยู่"]], tags: [["I'm afraid he's out", "afraid = เสียใจที่ต้องบอก"]], tip: "ขอสายแล้วเขาไม่อยู่ → I'm afraid he's out at the moment. (ขอโทษที่ต้องบอกว่า...)" },
  40: { links: [["What do you do", "I work in a bank", "ถามอาชีพ → ตอบอาชีพ"]], tags: [["I work in a bank", "ตอบอาชีพ"]], tip: "What do you do (for a living)? = ทำอาชีพอะไร → ตอบ I work in / I'm a ..." },
  41: { links: [["Why don't we", "Good idea", "ชวน → รับ"]], tags: [["Good idea", "ตอบรับ"]], tip: "Why don't we + V1? = ชวน (เรามา... กันไหม) → ตอบรับ Good idea." },
  42: { tense: "present-perfect-continuous", links: [["How long", "For about three years", "ถามระยะเวลา → for + ระยะเวลา"]], tags: [["have you been learning", "have been + V-ing"]], tip: "How long have you been + V-ing? → ตอบ For + ระยะเวลา / Since + จุดเวลา" },
  43: { tense: "present-perfect-continuous", links: [["five years", "for", "ระยะเวลา → for"], ["have been living", "for", "ต่อเนื่องถึงตอนนี้"]], tags: [["have been living", "have been + V-ing"]], tip: "for + ระยะเวลา (five years) · since + จุดเวลา (since 2020)" },
  44: { tense: "past-simple", links: [["yesterday", "called", "yesterday → อดีต"]], tags: [["called", "V2"]], tip: "yesterday = อดีตชัดเจน → past simple (called) ไม่ใช้ present perfect" },
  45: { links: [["a lot of", "homework", "นามนับไม่ได้"]], tags: [["homework", "นับไม่ได้ (ไม่มี s)"]], tip: "homework / information / advice = นามนับไม่ได้ → ไม่เติม s ไม่ใช้ a" },
  46: { links: [["don't have", "any", "ปฏิเสธ → any"]], tags: [["any", "ปฏิเสธ → any"]], tip: "ประโยคปฏิเสธ → any (ไม่ใช้ some)" },
  47: { links: [["The news", "is", "news = เอกพจน์"]], tags: [["is", "news → is"]], tip: "news เป็นนามนับไม่ได้ (เอกพจน์) → is (ไม่ใช่ are)" },
  48: { links: [["told me", "that", "told + คน + that + ประโยค"]], tags: [["that", "told me that ..."]], tip: "tell + คน + that + ประโยค (reported speech) · tell + คน + to + V1 = สั่ง" },
};
