// TOEIC Part 5 - Incomplete Sentences (เติมคำในประโยค): ข้อสอบฝึกที่เขียนขึ้นใหม่ในรูปแบบเดียวกับข้อสอบจริง (ไม่ได้คัดลอกจากข้อสอบของ ETS)
// รูปแบบ: { n, level: 'Part 5', topic, q, c, a, e }   · c = ตัวเลือก 4 ข้อ (A-D) · a = เลขตัวเลือกที่ถูก (เริ่มที่ 0)
// source: 'original' = เขียนเองสำหรับเว็บนี้ · ถ้าจะเพิ่มข้อสอบเก่าจากแหล่งอื่น ให้ใส่ source และ license ของแต่ละข้อ (ดู README หัวข้อ TOEIC)
// แก้ไข/เพิ่มข้อแล้วรัน: npm run manifest && npm run validate
window.CEFR_DATA = window.CEFR_DATA || {};
window.CEFR_DATA.toeic5 = [
  { n: 1, level: 'Part 5', topic: 'Word form', source: 'original', q: "The ______ of the new accounting software will begin next Monday.", c: ["install", "installing", "installation", "installed"], a: 2, e: "ช่องว่างตามหลัง the และตามด้วย of จึงต้องเป็นคำนาม → installation (การติดตั้ง)" },
  { n: 2, level: 'Part 5', topic: 'Tense', source: 'original', q: "Ms. Park ______ the quarterly report before the meeting yesterday.", c: ["finishes", "finished", "has finished", "will finish"], a: 1, e: "มี yesterday บอกอดีตที่จบแล้ว ใช้ past simple → finished" },
  { n: 3, level: 'Part 5', topic: 'Preposition', source: 'original', q: "All employees must submit their expense reports ______ Friday.", c: ["by", "in", "at", "for"], a: 0, e: "by + เวลา = ภายในเวลานั้น (เส้นตาย) → by Friday = ภายในวันศุกร์" },
  { n: 4, level: 'Part 5', topic: 'Conjunction', source: 'original', q: "______ the flight was delayed, the delegation arrived in time for the opening dinner.", c: ["Although", "Because", "Unless", "Therefore"], a: 0, e: "สองส่วนขัดแย้งกัน (บินล่าช้า แต่มาทัน) ใช้ Although = แม้ว่า · Therefore เป็นคำวิเศษณ์ ไม่ใช่คำเชื่อมประโยค" },
  { n: 5, level: 'Part 5', topic: 'Adverb', source: 'original', q: "The manager spoke ______ about the changes to the delivery schedule.", c: ["careful", "carefully", "care", "caring"], a: 1, e: "ขยายกริยา spoke ต้องใช้คำวิเศษณ์ → carefully (อย่างระมัดระวัง)" },
  { n: 6, level: 'Part 5', topic: 'Pronoun', source: 'original', q: "Mr. Lee asked the receptionist to send the package to ______ office.", c: ["he", "him", "his", "himself"], a: 2, e: "ต้องมีคำบอกความเป็นเจ้าของนำหน้านาม office → his (สำนักงานของเขา)" },
  { n: 7, level: 'Part 5', topic: 'Relative clause', source: 'original', q: "The candidate ______ résumé impressed the panel was offered the job.", c: ["who", "whom", "whose", "which"], a: 2, e: "whose + นาม = ...ซึ่งเป็นของ (résumé ของผู้สมัคร) ใช้ whose เมื่อแสดงความเป็นเจ้าของ" },
  { n: 8, level: 'Part 5', topic: 'Comparative', source: 'original', q: "This year's sales figures are ______ than last year's.", c: ["high", "higher", "highest", "the highest"], a: 1, e: "มี than เปรียบเทียบสองสิ่ง ใช้ comparative → higher" },
  { n: 9, level: 'Part 5', topic: 'Vocabulary', source: 'original', q: "Please ______ your seat belts while the aircraft is taking off.", c: ["fasten", "attach", "join", "tighten"], a: 0, e: "fasten a seat belt = คาดเข็มขัดนิรภัย (คำที่ใช้คู่กัน) · attach ใช้กับสิ่งที่แนบติดกับสิ่งอื่น" },
  { n: 10, level: 'Part 5', topic: 'Vocabulary', source: 'original', q: "Our supplier offers a 10 percent ______ on orders over $5,000.", c: ["discount", "discuss", "discard", "distance"], a: 0, e: "a 10 percent discount = ส่วนลด 10 เปอร์เซ็นต์ · discuss เป็นกริยา (หารือ), discard = ทิ้ง" },
  { n: 11, level: 'Part 5', topic: 'Passive', source: 'original', q: "The new vacation policy ______ to all staff by e-mail last week.", c: ["announced", "was announced", "has announced", "announcing"], a: 1, e: "นโยบายถูกประกาศ (ผู้ถูกกระทำ) และมี last week → past passive: was announced" },
  { n: 12, level: 'Part 5', topic: 'Gerund', source: 'original', q: "Ms. Tanaka is interested in ______ the marketing department.", c: ["join", "joining", "to join", "joined"], a: 1, e: "หลังคำบุพบท in ต้องใช้ V-ing → joining" },
  { n: 13, level: 'Part 5', topic: 'Infinitive', source: 'original', q: "The board decided ______ the contract with the current vendor.", c: ["renew", "renewing", "to renew", "renewed"], a: 2, e: "decide + to V → decided to renew (ตัดสินใจที่จะต่อสัญญา)" },
  { n: 14, level: 'Part 5', topic: 'Quantifier', source: 'original', q: "______ of the applicants have the required certification.", c: ["Few", "Little", "Much", "A little"], a: 0, e: "applicants นับได้พหูพจน์ ใช้ few (น้อยคน) · little / much / a little ใช้กับนามนับไม่ได้" },
  { n: 15, level: 'Part 5', topic: 'Preposition', source: 'original', q: "The seminar will be held ______ March 12 in the main conference hall.", c: ["in", "on", "at", "during"], a: 1, e: "วันที่เฉพาะเจาะจงใช้ on → on March 12" },
  { n: 16, level: 'Part 5', topic: 'Participle', source: 'original', q: "We were ______ by the large turnout at the product launch.", c: ["surprise", "surprising", "surprised", "surprises"], a: 2, e: "ความรู้สึกของคน (เรา) ใช้ V-ed → surprised · V-ing (surprising) ใช้กับสิ่งที่ทำให้รู้สึก" },
  { n: 17, level: 'Part 5', topic: 'Agreement', source: 'original', q: "The list of qualified candidates ______ posted on the notice board.", c: ["are", "is", "were", "have been"], a: 1, e: "ประธานจริงคือ list (เอกพจน์) ไม่ใช่ candidates → is" },
  { n: 18, level: 'Part 5', topic: 'Adverb', source: 'original', q: "The printer ______ breaks down when it is used for large jobs.", c: ["frequent", "frequency", "frequently", "more frequent"], a: 2, e: "ขยายกริยา breaks down ต้องใช้คำวิเศษณ์ → frequently (บ่อยครั้ง)" },
  { n: 19, level: 'Part 5', topic: 'Conjunction', source: 'original', q: "Applicants must submit ______ a résumé and a cover letter.", c: ["both", "either", "neither", "not only"], a: 0, e: "both A and B = ทั้ง A และ B · either ต้องคู่กับ or, neither ต้องคู่กับ nor" },
  { n: 20, level: 'Part 5', topic: 'Conditional', source: 'original', q: "If the shipment ______ by noon, we will be able to open on time.", c: ["arrive", "arrives", "arrived", "will arrive"], a: 1, e: "ประโยคเงื่อนไขจริงในอนาคต: If + present simple, ... will → arrives" },
  { n: 21, level: 'Part 5', topic: 'Word form', source: 'original', q: "Please contact the ______ department if you have questions about your pay.", c: ["account", "accounts", "accounting", "accountable"], a: 2, e: "accounting department = แผนกบัญชี (นามที่ใช้ขยายนาม department) · accountable = ต้องรับผิดชอบ" },
  { n: 22, level: 'Part 5', topic: 'Preposition', source: 'original', q: "The hotel is located ______ walking distance of the train station.", c: ["in", "within", "on", "among"], a: 1, e: "within walking distance of = อยู่ในระยะเดินถึง (วลีที่ใช้บ่อยมาก)" },
  { n: 23, level: 'Part 5', topic: 'Modal', source: 'original', q: "Visitors ______ sign in at the front desk before entering the building.", c: ["must", "would", "might", "could"], a: 0, e: "กฎ/ข้อบังคับ ใช้ must (ต้อง) · would, might, could ไม่ใช่ความหมายบังคับ" },
  { n: 24, level: 'Part 5', topic: 'Word form', source: 'original', q: "Mr. Gomez gave a very ______ presentation on renewable energy.", c: ["inform", "informative", "information", "informatively"], a: 1, e: "ตามหลัง very และขยายนาม presentation ต้องใช้คำคุณศัพท์ → informative (ให้ข้อมูลดี)" },
  { n: 25, level: 'Part 5', topic: 'Conjunction', source: 'original', q: "The meeting was postponed ______ the director was out of town.", c: ["because", "because of", "despite", "so that"], a: 0, e: "ตามด้วยประโยค (the director was...) ใช้ because · because of / despite ตามด้วยนามหรือ V-ing" },
  { n: 26, level: 'Part 5', topic: 'Preposition', source: 'original', q: "______ the heavy rain, the outdoor event went ahead as planned.", c: ["Despite", "Although", "Because", "However"], a: 0, e: "ตามด้วยนามวลี (the heavy rain) ใช้ Despite = แม้จะ · Although ต้องตามด้วยประโยค" },
  { n: 27, level: 'Part 5', topic: 'Phrasal verb', source: 'original', q: "Employees may ______ up to five unused vacation days to the following year.", c: ["carry over", "carry on", "carry off", "carry out"], a: 0, e: "carry over = ยกยอดไปปีถัดไป · carry on = ทำต่อ, carry out = ดำเนินการ" },
  { n: 28, level: 'Part 5', topic: 'Relative clause', source: 'original', q: "The conference room ______ we hold our weekly meetings is being renovated.", c: ["where", "who", "what", "whose"], a: 0, e: "ขยายสถานที่ (room) ใช้ where = ซึ่ง/ที่ (เป็นที่ที่เราจัดประชุม)" },
  { n: 29, level: 'Part 5', topic: 'Article', source: 'original', q: "The firm is looking for ______ assistant to help with filing and scheduling.", c: ["a", "an", "many", "several"], a: 1, e: "assistant ขึ้นต้นด้วยเสียงสระและเป็นนามนับได้เอกพจน์ → an · many / several ต้องตามด้วยนามพหูพจน์" },
  { n: 30, level: 'Part 5', topic: 'Word form', source: 'original', q: "The new software makes it ______ to track inventory across all warehouses.", c: ["easy", "easily", "ease", "easier than"], a: 0, e: "make it + คำคุณศัพท์ + to V → makes it easy to track (ทำให้การติดตามง่าย)" },
];
